{{- if .Values.sshKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virtual-machine.fullname" $ }}-ssh-keys
stringData:
  {{- range $k, $v := .Values.sshKeys }}
  key{{ $k }}: {{ quote $v }} 
  {{- end }}
{{- end }}
{{- if or .Values.cloudInit .Values.sshKeys }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "virtual-machine.fullname" . }}-cloud-init
stringData:
  userdata: |
    {{- if .Values.cloudInit }}
    {{-   .Values.cloudInit | nindent 4 }}
    {{- else if and (.Values.sshKeys) (not .Values.cloudInit) }}
    #cloud-config
    ssh_authorized_keys:
      {{- range .Values.sshKeys }}
      - {{ quote . }} 
      {{- end }}
    {{- end }}
{{- end }}
