## @section Common parameters

## @param size Persistent Volume size
## @param storageClass StorageClass used to store the data
## @param replicas Number of etcd replicas
##
size: 4Gi
storageClass: ""
replicas: 3

## Resources
## @param resources.cpu The number of CPU cores allocated
## @param resources.memory The amount of memory allocated
resources:
  cpu: 4
  memory: 1Gi
