metallb:
  crds:
    enabled: true
  controller:
    image:
      repository: ghcr.io/cozystack/cozystack/metallb-controller
      tag: v0.14.9@sha256:d8fa1a8147f844fb6add20a2147e9be6d1c26424748439c2648a0f6d8e10804d
  speaker:
    image:
      repository: ghcr.io/cozystack/cozystack/metallb-speaker
      tag: v0.14.9@sha256:a65437314ef23acf030afb44c3a25c5cb6ee813041e9b36ee7e0988a1e21b762
