{{- if and (not (eq .Values.topology "Client")) (.Values.filer.external) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-filer-external
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - name: swfs-filer-grpc
    port: 18888
    protocol: TCP
    targetPort: 18888
  selector:
    app.kubernetes.io/component: filer
    app.kubernetes.io/name: {{ $.Release.Name }}
{{- end }}
