## @section Common parameters
##
## @param replicas Number of replicas
replicas: 2
## @param resources Explicit CPU and memory configuration for each NATS replica. When left empty, the preset defined in `resourcesPreset` is applied.
resources: {}
  # resources:
  #   cpu: 4000m
  #   memory: 4Gi
## @param resourcesPreset Default sizing preset used when `resources` is omitted. Allowed values: nano, micro, small, medium, large, xlarge, 2xlarge.
resourcesPreset: "nano"
## @param storageClass StorageClass used to store the data
storageClass: ""
## @param external Enable external access from outside the cluster
external: false

## @section Application-specific parameters
##
## @param users [object] Users configuration (see example)
## Example:
## users:
##   user1:
##     password: strongpassword
##   user2: {}
users: {}

jetstream:
  ## @param jetstream.enabled Enable or disable Jetstream
  ## Set to true to enable Jetstream for persistent messaging in NATS.
  ## Default: true
  enabled: true
  ## @param jetstream.size Jetstream persistent storage size
  ## Specifies the size of the persistent storage for Jetstream (message store).
  ## Default: 10Gi
  size: 10Gi

config:
  ## @param config.merge Additional configuration to merge into NATS config (see example)
  ## Allows you to customize NATS server settings by merging additional configurations.
  ## For example, you can add extra parameters, configure authentication, or set custom settings.
  ## Default: {}
  ## example:
  ##
  ##   merge:
  ##     $include: ./my-config.conf
  ##     zzz$include: ./my-config-last.conf
  ##     server_name: nats
  ##     authorization:
  ##       token: << $TOKEN >>
  ##     jetstream:
  ##       max_memory_store: << 1GB >>
  ##
  ## will yield the config:
  ## {
  ##   include ./my-config.conf;
  ##   "authorization": {
  ##     "token": $TOKEN
  ##   },
  ##   "jetstream": {
  ##     "max_memory_store": 1GB
  ##   },
  ##   "server_name": "nats",
  ##   include ./my-config-last.conf;
  ## }
  merge: {}
  ## @param config.resolver Additional resolver configuration to merge into NATS config (see example)
  ## Allows you to customize NATS server settings by merging resolver configurations.
  ## Default: {}
  ## Example: https://github.com/nats-io/k8s/blob/94414664c254b0bbac3a07fc9693f6c4f8f88709/helm/charts/nats/values.yaml#L248-L270
  resolver: {}

