kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.37.0-alpha.1@sha256:434c36dfd6a28beab5df1c26c377c7db477b13548a9bd385e71b62aee2a8304c
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.37.0-alpha.1@sha256:434c36dfd6a28beab5df1c26c377c7db477b13548a9bd385e71b62aee2a8304c
