kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.36.0-alpha.1@sha256:ed1e64e671f6f7b9bc65ac5aff72477488aa01c9bed6c2fc2dcbbafd9a3b8b30
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.36.0-alpha.1@sha256:ed1e64e671f6f7b9bc65ac5aff72477488aa01c9bed6c2fc2dcbbafd9a3b8b30
