kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.35.0@sha256:bdc5f22adeae491b3476cdc23134a4b372edf72751c946e1db523c769f8fcfd5
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.35.0@sha256:bdc5f22adeae491b3476cdc23134a4b372edf72751c946e1db523c769f8fcfd5
