kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: latest@sha256:04aaf9acb6f49e0315295cd0c24655f28b74c6cf628fc6721758842a41d2deef
    repository: ghcr.io/aenix-io/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
