kamaji:
  etcd:
    deploy: false
  image:
    pullPolicy: IfNotPresent
    tag: v0.37.0-beta.1@sha256:7b88e2534912ac4b32b6fd9b51eb4571193d95ee696fa35a8dcd1ae2913e970b
    repository: ghcr.io/cozystack/cozystack/kamaji
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  extraArgs:
    - --migrate-image=ghcr.io/cozystack/cozystack/kamaji:v0.37.0-beta.1@sha256:7b88e2534912ac4b32b6fd9b51eb4571193d95ee696fa35a8dcd1ae2913e970b
